language: ruby
rvm:
 - 2.2.5
 - 2.3.1
 - jruby-9.0.1.0
 - jruby-9.0.5.0
gemfile:
- gemfiles/Gemfile.sidekiq-2.17.7
- gemfiles/Gemfile.sidekiq-3.1.0
- gemfiles/Gemfile.sidekiq-3.3.4
- gemfiles/Gemfile.sidekiq-4.0.2
script: bundle exec rake test
addons:
 code_climate:
  repo_token: b11e6d8ed83dd2e01424b088c469e2cef525a89e887414f81e6ee7f36b937a1d
after_success:
 - bundle exec codeclimate-test-reporter
